services:

  app:
    image: mcr.microsoft.com/devcontainers/base:bullseye
    # command: tail -f /dev/null
    networks:
      - custom_network

networks:
 custom_network:
   driver: bridge
