# This workflow will:
# 1) Build a Docker image from the latest commit to the main branch in the repository and tag it with 'latest'
# 2) Push the Docker image to DockerHub repository by the same name as the GitHub repository

name: Build Image and Push to DockerHub

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version (Must Match Git Tag. Leave blank for Latest)
        required: false
        type: string

  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
        
# env:
#   GIT_TAG: ${{ inputs.version }}

jobs:

  build-push:

    runs-on: ubuntu-latest

    steps:
      # If 'Version' was specified, this step will set the value of DOCKER_TAG to the specified version number
      - name: Sets DOCKER_TAG to specified version
        if: ${{ inputs.version != '' }}
        run: |
          echo "DOCKER_TAG=${{ inputs.version }}" >> $GITHUB_ENV

      # If 'Version' was NOT specified, this step will set the value of DOCKER_TAG to 'Latest'
      - name: Sets DOCKER_TAG to 'Latest'
        if: ${{ inputs.version == '' }}
        run: |
          echo "DOCKER_TAG=Latest" >> $GITHUB_ENV

      - name: "Say Hello Mona it's Monday"
        run: echo "DOCKER_TAG is $DOCKER_TAG"

        
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.version }}
      
      # Start by logging into DockerHub account
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      # QEMU is used by the docker/build-push-action action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      # Buildx is used by the docker/build-push-action action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      # # If 'Version' was specified, this will use the Docker metadata action to create a docker tag containing the git commit hash (sha)
      # - name: Docker meta
      #   id: meta
      #   uses: docker/metadata-action@v5.6.1
      #   with:
      #     images: |
      #       ${{ vars.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}
      #     tags: |
      #       type=sha
      
      # If 'Version' was specified, this action will build the docker image from the commit that's tagged with the specified version
      # and push the image to DockerHug with the specified version as the tag
      - name: Build and Push Specific Version
        if: ${{ inputs.version != '' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ inputs.version }}
          #tags: ${{ steps.meta.outputs.tags }}

       # If 'Version' was NOT specified, this action will build the docker image from the latest commit and push it to DockerHub using the 'Latest' tag
      - name: Build and Push Latest
        if: ${{ inputs.version == '' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest
