# This workflow will:
# 1) Build a Docker image from the latest commit to the main branch in the repository and tag it with 'latest'
# 2) Push the Docker image to DockerHub repository by the same name as the GitHub repository

name: Build Image and Push to DockerHub

on:
  workflow_dispatch:
    inputs:
      latest_version:
        description: Build Latest or Specific Version?
        type: choice
        options:
        - Latest
        - Specific Version
        default: 'Latest'
        required: true
      version:
        description: Version (Must Match Git Tag)
        required: false
        type: string

      # push:
      #   branches: [ "main" ]
      # pull_request:
      #   branches: [ "main" ]
        
env:
  TAG: ${{ inputs.latest_version == 'Latest' && '' || inputs.version }}
  # TAG: ${{ inputs.version }}

jobs:

  build-push:

    runs-on: ubuntu-latest

    env:
      Greeting: Hello

    steps:
      # # Uses the Docker metadata action to create a docker tag containing the git commit hash (sha)
      # - name: Docker meta
      #   id: meta
      #   uses: docker/metadata-action@v5.6.1
      #   with:
      #     images: |
      #       ${{ vars.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}
      #     tags: |
      #       type=sha 
      
      - name: "Say Hello Mona it's Monday"
        run: echo "latest_version input is ${{ inputs.latest_version }}. Tag is $TAG"
      
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ env.TAG }}
      
      # Start by logging into DockerHub account
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      # QEMU is used by the docker/build-push-action action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      # Buildx is used by the docker/build-push-action action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      # This action will build the docker image and push it to DockerHub using the tag generated in docker/metadata-action
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest
          #tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest,${{ steps.meta.outputs.tags }}
